### ISSUE TITLE
Request not working

### ISSUE THREAD

**Issue by dober2** [warren-bank/crx-Streamlare#1]
Hi,
 
i tried your curl:

> curl 'https://streamlare.com/api/video/get' \
  -H 'content-type: application/json;charset=UTF-8' -H 'accept: application/json' \
  -X POST  --data-binary '{"id":"b8K02DPmV03zygB1"}' \
  --insecure --compressed

> 
It gives back the same error i get, when i do this request for example in python. Do you maybe have a solution to get it working again?

**Comment by warren-bank** [comment]
you're right.. looks like they've changed something and now require a token

the above curl now returns: `{"status":"error","message":"Mismatch token"}`

I'll look into it a little later. I'm going to guess that the token they're referring to is probably from recaptcha.. which has a simple enough api to obtain a token when needed. TBD..

thanks for reporting!

**Comment by dober2** [comment]
Ok. Thank you.

**Comment by warren-bank** [comment]
I just began to look.. and (so far).. I have both good news and bad news:

<details>
  <summary>good news: figured out (with the help of Fiddler) how to successfully make the api request..</summary>

  ```text
    --------------------------------------------------------------------------------

    https://www.2embed.ru/embed/imdb/movie?id=tt10872600

    --------------------------------------------------------------------------------
    // https://streamlare.com/e/b8K02DPmV03zygB1

    network request:
    ================
    curl 'https://streamlare.com/api/video/get' \
      -H 'content-type: application/json;charset=UTF-8' -H 'accept: application/json' \
      -X POST  --data-binary '{"id":"b8K02DPmV03zygB1"}' \
      --insecure --compressed

    network response:
    =================
    {"status":"error","message":"Mismatch token"}

    --------------------------------------------------------------------------------
    // view-source:https://streamlare.com/e/b8K02DPmV03zygB1

    html content:
    =============
      <!-- CSRF Token -->
      <meta name="csrf-token" content="utWewLlbPSIIlIFhqAkpoWFoVcQuWxEMRHDHT7oc">

    --------------------------------------------------------------------------------
    // https://streamlare.com/e/b8K02DPmV03zygB1

    javascript console:
    ===================
    {
      const csrf_token = document.querySelector('meta[name="csrf-token"][content]').getAttribute('content')

      fetch('https://streamlare.com/api/video/get', {
        method: 'POST',
        mode: 'cors',
        credentials: 'same-origin',
        cache:  'no-cache',
        headers: {
          "content-type": "application/json",
          "accept":       "application/json",
          "X-CSRF-TOKEN": csrf_token
        },
        body: JSON.stringify({
          id: 'b8K02DPmV03zygB1'
        })
      })
      .then(response => response.text())
      .then(console.log)
    }

    console output:
    ===============
    {
      "status": "success",
      "message": "OK",
      "result": {
        "Original": {
          "label": "Original",
          "src": "W0dHQ0AJHBxEREQeA0EdQEBfA1cdUFxeHFJ7YQNQe34Ff0oKAFcAUEdXdEtCfGdqAnxgBklQAUREaXAGWVEBA0VXdApDZnZfR2BkR2lQZ3FiUmUKamIDdkppX1t7YmALS31ZYgN+WX5LfVl+B38DfXxnZ3kDUklyAGRleVJpAHFlYmt5dmFrcVxnWV9naVhlRH1dW0R9XgZDZntXS34BYQNhXXFgV11DWldZYUdhA2l5ZgNbAX0AfgF8d3VHYGZpYWBYZWpqZ318UWZHUmF7Q0FndXZHYmdXZVICV0p9ZktLYXtffFZ3aUBmA2VmaXZfYnxmV0N9Xgp9UntDcX8DBgVhZ31jYXZlBWdlfgJXdH12ZmI="
        }
      },
      "session": "utWewLlbPSIIlIFhqAkpoWFoVcQuWxEMRHDHT7oc"
    }

    --------------------------------------------------------------------------------
  ```
</details>

bad news: `result.Original.src` in the JSON response isn't a URL (nor is it a base64-encoded URL).. so I'll need to continue looking into their methodology to figure out how this value is used to derive a video URL

**Comment by warren-bank** [comment]
OK.. done!

I have to give them credit.. streamlare is making a good effort to obfuscate the video url. Of course, I'm not sure what the point ultimately is.. since the end-product of all their encoding and decoding is a URL that's easy enough to obtain.. either using Chrome devtools, a proxy like _fiddler_, or just simply from _jwplayer_'s configuration (ex: `jwplayer().getConfig().playlist[0].file`).

In any case.. all of the details are contained by 2x text files with my notes:
1) [csrf-token.txt](https://github.com/warren-bank/crx-Streamlare/blob/webmonkey-userscript/es5/webmonkey-userscript/notes/2-csrf-token.txt)
2) [decoding-result-Original-src.txt](https://github.com/warren-bank/crx-Streamlare/blob/webmonkey-userscript/es5/webmonkey-userscript/notes/3-decoding-result-Original-src.txt)

summary:
* the api request requires the header: `X-CSRF-TOKEN`
* the value returned is encoded
  - the methodology to decode isn't overly complicated

[`v1.0.2`](https://github.com/warren-bank/crx-Streamlare/commit/7a93130d5fd8a7e7e3eaf8a75c9209a906d430db) implements these changes.

**Comment by AvAkanksh** [comment]
are you able to decode the url, I have seen your code but I am not able to understand how do we decode the JSON response to a URL.

Can you please explain it in detail.

Thank you in Advance.

Edited:
Actually, I understood how you got the link to the URL. but the thing is I want to play that link using my mpv player, so when I copy that URL on to my mpv player its not working. 
eg URL:
[link to the video](https://larecontent.com/video?token=SBFGQV8RCRFbR0dDQAlvHG8cREREHkZURQYLCwsEHUBAXwNXHVBcXm8cQ3BCfmADYV9XY39ndAcGXwVqWWF-VG8cAgUFBwYDCwYFCm8cAQcDBgkBAwJvHABpUnprQFlbd0d5dwZsBQdjWEtdWQV0AB5QQHlKbGlJf3RUY3IeWH9iBEpncGpQWwBWClJ-Vl95WAV4QlZkA2dcflFBfFlaYQt6dHZ9CkNAZ0F2fXcCREZmVWoDfEEGHnBqdmNsZ2Fde0RWVXVrVGNyfQR1SktdWgtaBQZ9XmsKewVpUVh5WAJ-Z2BWdQsLA2JeSgseVV0CelsGA2sBflJ7dndqUntRVEliZX9LaQZiY3UeBHRaY0pnWFJEe35Xd2RrYAQLRQQLa0YHZEJfAHVUSnRpd1x0XEtnS2xmAH94XEceYF5pB1l9XmMGA2ZHeHhYeVFLW0l9awVsakJQdHl4Q2Zffn8BR2JAfXh9BgVqcltXVkoHZ2xeZ3tXWVBCZ1dXY31QdXt-e2ALbxxlWlhBUl1HGGFcXVIYFgELAQMBARYBChhnVl9GVEYYe2IYe3dhWkMYSwEFBxhycnAYBAMDfnEYdmBGUR1eWEUdXkMHDEBHQVZSXg4CER8RWkMRCREBBwMGCQEDAhFO)
So can you please share a work around for that, it would be greatly helpful for me.

Thank you once again.

**Comment by warren-bank** [comment]
[v1.0.3](https://github.com/warren-bank/crx-Streamlare/commit/af9aa9145ca0b93935356e8ff1efe100cf0f3456) is an update to compensate for some significant changes to the website.. it's now working again
